### ISSUE TITLE
Testar imagem enxuta do jupyterlab

### ISSUE THREAD

**Issue by felipbizz** [felipbizz/mle-tech-challenge-4#3]
Segue exemplo:

```dockerfile
FROM alpine:latest AS base

# Instala dependências do sistema necessárias para o uv e Python
RUN apk add --no-cache curl bash build-base python3 py3-pip

# Instala o uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de dependências (se existirem)
COPY pyproject.toml uv.lock ./

# Instala o Python 3.12 com uv
RUN uv python install 3.12

# Cria um ambiente virtual
RUN uv venv .venv

# Ativa o ambiente virtual e instala o JupyterLab usando uv
RUN .venv/bin/activate && uv pip install jupyterlab

# Gera um hash SHA-256 para um token fixo (substitua "seu_token_fixo" pelo seu token real)
RUN echo -n "seu_token_fixo" | sha256sum | awk '{print $1}' > token.txt

# Copia o código da aplicação (se houver)
COPY . .

# Expõe a porta 8888 para o JupyterLab
EXPOSE 8888

# Define o comando para iniciar o JupyterLab com o token fixo
CMD .venv/bin/jupyter lab --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token=$(cat token.txt)
```

**Comment by felipbizz** [comment]
Exemplo pyproject
```toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jupyterlab-alpine"  # Nome do seu projeto (pode ser qualquer um)
version = "0.1.0"           # Versão inicial
description = "JupyterLab em Alpine Linux com uv"
authors = [{ name = "Seu Nome", email = "seu.email@exemplo.com" }]
dependencies = [
    "jupyterlab",
]
dynamic = ["dependencies"]

[tool.uv]
venv = ".venv" # path do ambiente virtual
```
